name: check

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run deno fmt
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint
