name: check

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run deno fmt
        run: deno fmt --check

      - name: Run deno lint
        run: deno lint

      - name: Check license headers
        run: |
          deno run -A --no-check https://deno.land/x/anzu@1.0.0/src/cli.ts \
           -i ./ "/.+\.ts/" \
           -l "// Copyright 2023 Samuel Kopp. All rights reserved. MIT license." \
           -p
